(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const km=(a,b)=>{const R=6371,r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon),x=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
const CRM_KEY='nexaro-crm-v2-0',ROUTE_KEY='nexaro-active-day-route-v1';
const style=`#areaSearchResults{margin-top:12px}.area-result-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.area-result-list{display:grid;gap:8px}.area-result{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px 12px;border:1px solid var(--border,#26344a);border-radius:12px;background:rgba(255,255,255,.025)}.area-result .meta{margin-top:3px}.area-result-actions{display:flex;gap:7px}.area-result-actions button{white-space:nowrap}.area-loading{padding:14px;text-align:center}.area-error{padding:12px;border:1px solid #6b2d2d;border-radius:12px;background:rgba(180,50,50,.08)}.day-route-box{margin-top:12px}.day-route-list{display:grid;gap:7px}.day-route-item{display:flex;align-items:center;gap:9px;padding:9px 10px;border:1px solid var(--border,#26344a);border-radius:10px}.day-route-item b{flex:1}.day-route-actions{display:flex;gap:7px;margin-top:10px}.day-route-actions button{flex:1}.route-added{opacity:.65}.route-added .area-result-actions button:first-child{display:none}@media(max-width:650px){.area-result{align-items:stretch;flex-direction:column}.area-result-actions{width:100%;display:grid;grid-template-columns:1fr 1fr}.area-result-actions button{width:100%;padding:8px 10px}.day-route-actions{display:grid;grid-template-columns:1fr}.day-route-item{align-items:flex-start;flex-direction:column}}`;
function inject(){if($('#areaFixStyle'))return;const s=document.createElement('style');s.id='areaFixStyle';s.textContent=style;document.head.appendChild(s)}
function hideLegacy(){const p=$('#prospectList');const c=p?.closest('.card');if(c)c.style.display='none'}
function address(p){return p.address||[p.street,p.housenumber,p.zip,p.city].filter(Boolean).join(' ')}
function readRoute(){try{const x=JSON.parse(localStorage.getItem(ROUTE_KEY)||'{}');return {...x,items:Array.isArray(x.items)?x.items:[]}}catch{return{date:'',area:'',items:[]}}}
function writeRoute(r){localStorage.setItem(ROUTE_KEY,JSON.stringify(r))}
function routeDate(){return $('#routeDate')?.value||new Date().toISOString().slice(0,10)}
function routeLabel(d){try{return new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}catch{return d||''}}
function renderDayRoute(){const r=readRoute(),box=$('#dayRouteBox');if(!box)return;const items=r.items||[];box.innerHTML=`<div class="area-result-head"><h3>🚗 Tagesroute</h3><span class="badge">${items.length}/20</span></div>${items.length?`<div class="meta" style="margin-bottom:8px">${esc(routeLabel(r.date))}${r.area?' · '+esc(r.area):''}</div><div class="day-route-list">${items.map((p,i)=>`<div class="day-route-item"><span>${i+1}.</span><b>${esc(p.name)}</b><span class="meta">${Number(p.distance||0).toFixed(1)} km</span></div>`).join('')}</div><div class="day-route-actions"><button type="button" id="openDayRoute">🗺️ Komplette Route öffnen</button><button type="button" class="secondary" id="clearDayRoute">Route leeren</button></div>`:`<div class="muted">Noch keine Gebietstreffer in der Tagesroute. Mit „Lead + Route“ wird der Treffer automatisch hinzugefügt.</div>`}`;$('#openDayRoute')?.addEventListener('click',openDayRoute);$('#clearDayRoute')?.addEventListener('click',()=>{if(!items.length)return;writeRoute({date:r.date,area:r.area,items:[]});renderDayRoute();renderResultsButtons()})}
function renderResultsButtons(){document.querySelectorAll('[data-area-route]').forEach(b=>{try{const p=JSON.parse(decodeURIComponent(b.dataset.areaRoute)),r=readRoute(),exists=r.items.some(x=>x.leadId&&p.leadId&&x.leadId===p.leadId)||r.items.some(x=>(x.name||'').toLowerCase()===(p.name||'').toLowerCase());const card=b.closest('.area-result');card?.classList.toggle('route-added',exists);b.textContent=exists?'✓ In Tagesroute':'🗺️ Lead + Route'}catch(e){}})}
function openDayRoute(){const r=readRoute(),items=r.items||[];if(!items.length)return;const pts=items.map(x=>x.lat&&x.lon?`${x.lat},${x.lon}`:address(x)).filter(Boolean);if(!pts.length)return;const destination=encodeURIComponent(pts[pts.length-1]),waypoints=pts.slice(0,-1).map(encodeURIComponent).join('|');let u=`https://www.google.com/maps/dir/?api=1&destination=${destination}&travelmode=driving`;if(waypoints)u+=`&waypoints=${waypoints}`;window.open(u,'_blank','noopener')}
async function geocode(q){const urls=[`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&countrycodes=de&q=${encodeURIComponent(q)}`,`https://photon.komoot.io/api/?q=${encodeURIComponent(q)}&limit=5&lang=de`];for(const u of urls){try{const rr=await fetch(u,{headers:{Accept:'application/json'}});if(!rr.ok)continue;const j=await rr.json();const a=Array.isArray(j)?j:j.features||[];const out=a.map(x=>Array.isArray(j)?{lat:+x.lat,lon:+x.lon,label:x.display_name||q,address:x.address||{}}:{lat:+x.geometry.coordinates[1],lon:+x.geometry.coordinates[0],label:x.properties?.label||x.properties?.name||q,address:x.properties||{}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));if(out.length)return out}catch(e){}}throw Error('Geocoding fehlgeschlagen')}
async function queryEndpoint(endpoint,query){const rr=await fetch(endpoint+'?data='+encodeURIComponent(query),{headers:{Accept:'application/json'}});if(!rr.ok)throw Error('HTTP '+rr.status);const j=await rr.json();return j.elements||[]}
async function prospects(area,radiusKm){const rad=Math.max(1,+radiusKm||5)*1000;const q=`[out:json][timeout:30];(nwr["name"]["shop"](around:${rad},${area.lat},${area.lon});nwr["name"]["amenity"~"cafe|restaurant|fast_food|bar|pub|bakery|fuel|pharmacy"](around:${rad},${area.lat},${area.lon});nwr["name"]["craft"](around:${rad},${area.lat},${area.lon});nwr["name"]["office"](around:${rad},${area.lat},${area.lon}););out center tags;`;const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];let last;for(const ep of endpoints){try{const raw=await queryEndpoint(ep,q);const seen=new Set();return raw.map(x=>{const t=x.tags||{};return{name:t.name,address:[t['addr:street'],t['addr:housenumber'],t['addr:postcode'],t['addr:city']].filter(Boolean).join(' '),street:t['addr:street']||'',housenumber:t['addr:housenumber']||'',zip:t['addr:postcode']||'',city:t['addr:city']||'',contact:t['contact:name']||t['contact:person']||'',phone:t['contact:phone']||t.phone||'',email:t['contact:email']||t.email||'',lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon,category:t.shop||t.amenity||t.craft||t.office||''}}).filter(x=>x.name&&Number.isFinite(x.lat)&&Number.isFinite(x.lon)).filter(x=>{const k=x.name.toLowerCase()+'|'+x.lat.toFixed(5)+'|'+x.lon.toFixed(5);if(seen.has(k))return false;seen.add(k);return true}).map(x=>({...x,distance:km(area,x)})).sort((a,b)=>a.distance-b.distance).slice(0,60)}catch(e){last=e}}throw last||Error('Öffentliche Unternehmensdatenbank nicht erreichbar')}
function leadValues(p){return{fCompany:p.name||'',fIndustry:p.category||'Sonstiges',fContact:p.contact||'',fPhone:p.phone||'',fEmail:p.email||'',fStreet:[p.street,p.housenumber].filter(Boolean).join(' '),fZip:p.zip||'',fCity:p.city||'',fProvider:'',fTerminal:'',fProduct:'Noch offen',fPriority:'Hoch',fNext:'Gebietstreffer – Erstkontakt',fNotes:`Öffentlicher Gebietstreffer · OpenStreetMap · ${p.distance?.toFixed?.(1)||''} km Entfernung`}}
function fillForm(p){if(typeof window.lead!=='function')return false;window.lead();setTimeout(()=>{for(const [id,v] of Object.entries(leadValues(p))){const el=$('#'+id);if(el)el.value=v}},0);return true}
function saveLeadAndRoute(p){if(typeof window.lead!=='function')return;window.lead();setTimeout(()=>{for(const [id,v] of Object.entries(leadValues(p))){const el=$('#'+id);if(el)el.value=v}const form=$('#leadForm');if(form){const req=[...form.querySelectorAll('[required]')];req.forEach(x=>x.required=false);form.requestSubmit();req.forEach(x=>x.required=true)}setTimeout(()=>{let leadId='';try{const s=JSON.parse(localStorage.getItem(CRM_KEY)||'{}');const candidates=Array.isArray(s.leads)?s.leads:[];const hit=candidates.find(x=>(x.company||'').trim().toLowerCase()===(p.name||'').trim().toLowerCase());if(hit)leadId=hit.id||''}catch(e){}const r=readRoute();const item={leadId,name:p.name,address:address(p),street:p.street||'',housenumber:p.housenumber||'',zip:p.zip||'',city:p.city||'',lat:p.lat,lon:p.lon,distance:p.distance||0};if(!r.items.some(x=>(leadId&&x.leadId===leadId)||((x.name||'').toLowerCase()===(item.name||'').toLowerCase()))){if(r.items.length<20)r.items.push(item)}r.date=routeDate();r.area=$('#areaStatus')?.textContent||r.area||'';writeRoute(r);renderDayRoute();renderResultsButtons();const pts=r.items.map(x=>x.lat&&x.lon?`${x.lat},${x.lon}`:address(x)).filter(Boolean);if(pts.length){const dest=encodeURIComponent(pts[pts.length-1]);const waypoints=pts.slice(0,-1).map(encodeURIComponent).join('|');let u=`https://www.google.com/maps/dir/?api=1&destination=${dest}&travelmode=driving`;if(waypoints)u+=`&waypoints=${waypoints}`;window.open(u,'_blank','noopener')}},650)},50)}
async function run(area){const q=$('#areaQuery'),r=$('#areaRadius'),status=$('#areaStatus'),body=$('#areaResultBody'),count=$('#areaResultCount');window.area=area;status.textContent=area.label;body.innerHTML=`<div class="area-loading">📍 ${esc(area.label)}<br>Unternehmen im Gebiet werden geladen …</div>`;count.textContent='…';try{const items=await prospects(area,r.value);let existing=new Set();try{const s=JSON.parse(localStorage.getItem(CRM_KEY)||'{}');existing=new Set((s.leads||[]).map(l=>(l.company||'').toLowerCase()))}catch(e){}const fresh=items.filter(x=>!existing.has(x.name.toLowerCase()));count.textContent=fresh.length;body.innerHTML=`<div class="area-location"><b>📍 ${esc(area.label)}</b><span class="meta">${fresh.length} Treffer im Radius von ${esc(r.value)} km</span></div><div class="area-result-list">${fresh.map(p=>`<div class="area-result"><div><b>${esc(p.name)}</b><div class="meta">${esc(address(p)||p.category||'Adresse nicht angegeben')} · ${p.distance.toFixed(1)} km${p.phone?' · ☎ '+esc(p.phone):''}</div></div><div class="area-result-actions"><button type="button" class="secondary" data-area-lead="${encodeURIComponent(JSON.stringify(p))}">＋ Lead</button><button type="button" data-area-route="${encodeURIComponent(JSON.stringify(p))}">🗺️ Lead + Route</button></div></div>`).join('')||'<div class="empty">Keine passenden Unternehmen gefunden.</div>'}</div>`;renderResultsButtons()}catch(e){count.textContent='0';body.innerHTML=`<div class="area-location"><b>📍 ${esc(area.label)}</b><span class="meta">Suchzentrum gefunden · Radius ${esc(r.value)} km</span></div><div class="area-error">Die Unternehmensdatenbank antwortet gerade nicht. Bitte erneut versuchen.</div>`}}
function setup(){const screen=$('#area'),search=$('#areaQuery')?.closest('.card');if(!screen||!search)return;inject();hideLegacy();let box=$('#areaSearchResults');if(!box){box=document.createElement('div');box.id='areaSearchResults';box.className='card';box.innerHTML='<div class="area-result-head"><h3>Gebietstreffer</h3><span class="badge" id="areaResultCount">0</span></div><div id="areaResultBody"><div class="muted">PLZ oder Ort eingeben und „Gebiet suchen“ wählen.</div></div>';search.after(box)}let routeBox=$('#dayRouteBox');if(!routeBox){routeBox=document.createElement('div');routeBox.id='dayRouteBox';routeBox.className='card day-route-box';box.after(routeBox)}renderDayRoute();const btn=$('#searchArea'),loc=$('#useLocation'),query=$('#areaQuery');if(!btn||btn.dataset.areaFixBound==='1')return;btn.dataset.areaFixBound='1';const searchNow=async(e)=>{e?.preventDefault();e?.stopPropagation();const v=query.value.trim();if(!v){query.focus();return}btn.disabled=true;btn.textContent='Suche läuft …';$('#areaStatus').textContent='Ort/PLZ wird gesucht …';try{const hits=await geocode(v);if(!hits.length)throw Error('Geocoding fehlgeschlagen');await run(hits[0])}catch(e){$('#areaStatus').textContent='Ort/PLZ nicht gefunden';$('#areaResultCount').textContent='0';$('#areaResultBody').innerHTML='<div class="area-error">Ort oder PLZ konnte nicht gefunden werden.</div>'}finally{btn.disabled=false;btn.textContent='Gebiet suchen'}};btn.addEventListener('click',searchNow,true);query.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();searchNow(e)}});loc?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();navigator.geolocation?.getCurrentPosition(p=>run({lat:p.coords.latitude,lon:p.coords.longitude,label:'Mein Standort'}),()=>{if(typeof window.toast==='function')toast('Standortzugriff nicht möglich.')})},true);box.addEventListener('click',e=>{const a=e.target.closest('[data-area-lead]'),b=e.target.closest('[data-area-route]');if(a)return fillForm(JSON.parse(decodeURIComponent(a.dataset.areaLead)));if(b)return saveLeadAndRoute(JSON.parse(decodeURIComponent(b.dataset.areaRoute)))})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
function loadCss(href){if(document.querySelector(`link[data-nx="${href}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.nx=href;document.head.appendChild(l)}
function loadJs(src){if(document.querySelector(`script[data-nx="${src}"]`))return;const s=document.createElement('script');s.src=src;s.dataset.nx=src;document.head.appendChild(s)}
loadCss('./light-theme.css?v=1');loadCss('./sumup-pro.css?v=1');loadJs('./sumup-pro.js?v=1');loadJs('./sumup-knowledge.js?v=1');loadJs('./sumup-pricing-policy.js?v=2');
})();