(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const km=(a,b)=>{const R=6371,r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon),x=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
const style=`#areaSearchResults{margin-top:12px}.area-result-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.area-result-head h3{margin:0}.area-location{padding:10px 12px;border:1px solid var(--border,#26344a);border-radius:12px;background:rgba(255,255,255,.03);margin-bottom:10px}.area-location b{display:block;margin-bottom:3px}.area-result-list{display:grid;gap:8px}.area-result{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px 12px;border:1px solid var(--border,#26344a);border-radius:12px;background:rgba(255,255,255,.025)}.area-result .meta{margin-top:3px}.area-result button{flex:0 0 auto}.area-loading{padding:14px;text-align:center}.area-error{padding:12px;border:1px solid #6b2d2d;border-radius:12px;background:rgba(180,50,50,.08)}#area .area-search-card{margin-bottom:0}#area .area-results-card{border-top-left-radius:12px;border-top-right-radius:12px}#area .area-customers-card{margin-top:12px}#area .area-saved-card{margin-top:12px}#area .area-filters{margin-top:12px}@media(max-width:650px){.area-result{align-items:flex-start}.area-result button{padding:8px 10px}.area-result{flex-direction:column}.area-result button{width:100%}}`;
function inject(){if($('#areaFixStyle'))return;const s=document.createElement('style');s.id='areaFixStyle';s.textContent=style;document.head.appendChild(s)}
function hideLegacyProspects(){const p=$('#prospectList');const card=p?.closest('.card');if(card)card.style.display='none'}
function setup(){const screen=$('#area'),searchCard=$('#areaQuery')?.closest('.card');if(!screen||!searchCard)return;inject();hideLegacyProspects();let box=$('#areaSearchResults');if(!box){box=document.createElement('div');box.id='areaSearchResults';box.className='card';box.innerHTML='<div class="area-result-head"><h3>Gebietstreffer</h3><span class="badge" id="areaResultCount">0</span></div><div id="areaResultBody"><div class="muted">PLZ oder Ort eingeben und „Gebiet suchen“ wählen.</div></div>';searchCard.after(box)}
const query=$('#areaQuery'),radius=$('#areaRadius'),status=$('#areaStatus'),body=$('#areaResultBody'),count=$('#areaResultCount'),searchBtn=$('#searchArea'),locationBtn=$('#useLocation');
async function geocode(q){const urls=[`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&countrycodes=de&q=${encodeURIComponent(q)}`,`https://photon.komoot.io/api/?q=${encodeURIComponent(q)}&limit=5&lang=de`];for(const u of urls){try{const r=await fetch(u,{headers:{'Accept':'application/json'}});if(!r.ok)continue;const j=await r.json();const a=Array.isArray(j)?j:j.features||[];const out=a.map(x=>Array.isArray(j)?{lat:+x.lat,lon:+x.lon,label:x.display_name||q,address:x.address||{}}:{lat:+x.geometry.coordinates[1],lon:+x.geometry.coordinates[0],label:x.properties?.name?[x.properties.name,x.properties.city||x.properties.town,x.properties.state].filter(Boolean).join(', '):x.properties?.label||q,address:x.properties||{}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));if(out.length)return out}catch(e){}}throw new Error('Geocoding fehlgeschlagen')}
async function prospects(area){const rad=(+radius.value||5)*1000;const u=`https://overpass-api.de/api/interpreter?data=[out:json][timeout:25];(nwr["name"]["shop"](around:${rad},${area.lat},${area.lon});nwr["name"]["amenity"~"cafe|restaurant|fast_food|bar|pub|bakery"](around:${rad},${area.lat},${area.lon}););out center tags 60;`;const r=await fetch(u);if(!r.ok)throw new Error('Overpass');const j=await r.json();return (j.elements||[]).map(x=>({name:x.tags?.name,address:[x.tags?.['addr:street'],x.tags?.['addr:housenumber'],x.tags?.['addr:postcode'],x.tags?.['addr:city']].filter(Boolean).join(' '),lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon,category:x.tags?.shop||x.tags?.amenity||''})).filter(x=>x.name&&Number.isFinite(x.lat)&&Number.isFinite(x.lon)).slice(0,30)}
function renderLocation(area){body.innerHTML=`<div class="area-location"><b>📍 ${esc(area.label)}</b><span class="meta">Suchzentrum gefunden · Radius ${esc(radius.value)} km</span></div><div class="area-loading">Unternehmen im Gebiet werden geladen …</div>`;count.textContent='…'}
function renderProspects(items,area){const existing=new Set((window.S?.leads||[]).map(l=>(l.company||'').toLowerCase()));const fresh=items.filter(x=>!existing.has(x.name.toLowerCase()));count.textContent=fresh.length;body.innerHTML=`<div class="area-location"><b>📍 ${esc(area.label)}</b><span class="meta">${fresh.length} passende Unternehmen im Radius von ${esc(radius.value)} km</span></div><div class="area-result-list">${fresh.map(p=>`<div class="area-result"><div><b>${esc(p.name)}</b><div class="meta">${esc(p.address||p.category||'Adresse nicht angegeben')} · ${km(area,p).toFixed(1)} km</div></div><button class="secondary" data-area-prospect="${encodeURIComponent(JSON.stringify(p))}">＋ Lead</button></div>`).join('')||'<div class="empty">Keine passenden Unternehmen gefunden.</div>'}</div>`}
async function run(area){window.area=area;status.textContent=area.label;renderLocation(area);try{const items=await prospects(area);renderProspects(items,area)}catch(e){count.textContent='0';body.innerHTML=`<div class="area-location"><b>📍 ${esc(area.label)}</b><span class="meta">Suchzentrum gefunden · Radius ${esc(radius.value)} km</span></div><div class="area-error">Die Standortsuche funktioniert, aber die öffentliche Unternehmensdatenbank antwortet gerade nicht. Bitte erneut suchen.</div>`}try{if(typeof window.makeRoute==='function')await window.makeRoute()}catch(e){}}
searchBtn.onclick=async()=>{const q=query.value.trim();if(!q){query.focus();return typeof window.toast==='function'?toast('Bitte PLZ oder Ort eingeben'):void 0}searchBtn.disabled=true;searchBtn.textContent='Suche läuft …';status.textContent='Ort/PLZ wird gesucht …';body.innerHTML='<div class="area-loading">📍 Standort wird gesucht …</div>';try{const hits=await geocode(q);await run(hits[0])}catch(e){status.textContent='Ort/PLZ nicht gefunden';count.textContent='0';body.innerHTML='<div class="area-error">Ort oder PLZ konnte nicht gefunden werden. Bitte z. B. „15757 Halbe“ oder „Berlin“ eingeben.</div>'}finally{searchBtn.disabled=false;searchBtn.textContent='Gebiet suchen'}};
query.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchBtn.click()}};
locationBtn.onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{locationBtn.disabled=true;locationBtn.textContent='📍 Standort wird ermittelt …';await run({lat:p.coords.latitude,lon:p.coords.longitude,label:'Mein Standort'});locationBtn.disabled=false;locationBtn.textContent='📍 Mein Standort'},()=>{if(typeof window.toast==='function')toast('Standortzugriff nicht möglich. Bitte PLZ oder Ort suchen.')});
box.addEventListener('click',e=>{const b=e.target.closest('[data-area-prospect]');if(!b)return;const p=JSON.parse(decodeURIComponent(b.dataset.areaProspect));if(typeof window.lead==='function'){window.lead();setTimeout(()=>{if($('#fCompany'))$('#fCompany').value=p.name;if($('#fStreet'))$('#fStreet').value=(p.address||'').replace(/\s+\d+\s+\d{5}\s+.*$/,'');const m=(p.address||'').match(/(\d{5})\s+(.+)$/);if(m){if($('#fZip'))$('#fZip').value=m[1];if($('#fCity'))$('#fCity').value=m[2]}},0)}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
