/* neXaro Händlerverwaltung – safe extension for existing CRM */
(function(){
'use strict';
const KEY='nexaro-dealers-v1',MIN=15,MAX=25;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const clamp=v=>Math.min(MAX,Math.max(MIN,Number(v)||25));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
let dealers=load(),currentId=localStorage.getItem(KEY+'-current')||'';
if(!dealers.length){dealers=[{id:uid(),company:'Beispiel Händler',contact:'',email:'',margin:25,active:true}];save(dealers)}
if(!dealers.some(d=>d.id===currentId))currentId=dealers[0]?.id||'';
const current=()=>dealers.find(d=>d.id===currentId)||dealers[0];
function applyMargin(){const d=current();if(!d)return;const el=document.getElementById('vapeMarkup'),out=document.getElementById('vapeMarkupValue');if(el){el.value=clamp(d.margin);el.dispatchEvent(new Event('input',{bubbles:true}))}if(out)out.textContent=clamp(d.margin)+'%';localStorage.setItem(KEY+'-current',d.id)}
const style=document.createElement('style');style.textContent='.nx-dealer-modal{position:fixed;inset:0;background:rgba(0,0,0,.62);z-index:99999;display:flex;align-items:center;justify-content:center;padding:16px}.nx-dealer-box{width:min(760px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.3);color:#111}.nx-dealer-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.nx-dealer-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.nx-dealer-grid label{display:flex;flex-direction:column;gap:6px;font-weight:600}.nx-dealer-grid input,.nx-dealer-grid select{padding:11px;border:1px solid #ccd2da;border-radius:10px;font:inherit}.nx-dealer-list{display:grid;gap:10px;margin:14px 0}.nx-dealer-card{border:1px solid #d8dde5;border-radius:14px;padding:12px}.nx-dealer-card.active{border-width:2px}.nx-dealer-row{display:flex;justify-content:space-between;align-items:center;gap:10px}.nx-dealer-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.nx-dealer-actions button{padding:9px 12px;border-radius:9px;border:1px solid #cbd2dc;background:#fff}.nx-dealer-actions .primary{background:#111827;color:#fff}.nx-dealer-margin{margin-top:8px}.nx-dealer-margin input{width:100%}.nx-dealer-note{font-size:12px;color:#667085;margin-top:10px}.nx-dealer-badge{font-size:12px;padding:4px 8px;border-radius:99px;background:#eef2f6}.nx-dealer-new{margin-top:14px;padding-top:14px;border-top:1px solid #e4e7ec}.nx-dealer-close{border:0;background:transparent;font-size:26px;line-height:1;cursor:pointer}.nx-dealer-toolbar{display:flex;gap:8px;flex-wrap:wrap}.nx-dealer-toolbar button{padding:10px 12px;border-radius:10px;border:1px solid #ccd2da;background:#fff}.nx-dealer-toolbar button.primary{background:#111827;color:#fff}@media(max-width:600px){.nx-dealer-grid{grid-template-columns:1fr}.nx-dealer-box{padding:15px;border-radius:16px}}';document.head.appendChild(style);
function renderModal(){let modal=document.getElementById('nxDealerModal');if(modal)modal.remove();modal=document.createElement('div');modal.id='nxDealerModal';modal.className='nx-dealer-modal';modal.innerHTML='<div class="nx-dealer-box"><div class="nx-dealer-head"><div><div style="font-size:12px;letter-spacing:.08em;font-weight:700">VAPE · INTERN</div><h2 style="margin:3px 0">Händlerverwaltung</h2><div class="nx-dealer-note">Händlerprofile und individuelle Vape-Marge. Diese Daten sind nur lokal im CRM.</div></div><button class="nx-dealer-close" aria-label="Schließen">×</button></div><div class="nx-dealer-toolbar"><button class="primary" id="nxNewDealer">＋ Händler anlegen</button><button id="nxApplyCurrent">Aktuellen Händler verwenden</button></div><div class="nx-dealer-list" id="nxDealerList"></div><div class="nx-dealer-new" id="nxDealerForm" style="display:none"><h3 style="margin-top:0">Neuer Händler</h3><div class="nx-dealer-grid"><label>Firma<input id="nxCompany" placeholder="Firma"></label><label>Ansprechpartner<input id="nxContact" placeholder="Name"></label><label>E-Mail<input id="nxEmail" type="email" placeholder="E-Mail"></label><label>Status<select id="nxActive"><option value="1">Aktiv</option><option value="0">Inaktiv</option></select></label></div><div class="nx-dealer-actions"><button class="primary" id="nxSaveDealer">Händler speichern</button><button id="nxCancelDealer">Abbrechen</button></div></div></div>';document.body.appendChild(modal);modal.querySelector('.nx-dealer-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};document.getElementById('nxNewDealer').onclick=()=>{document.getElementById('nxDealerForm').style.display='block';document.getElementById('nxCompany').focus()};document.getElementById('nxCancelDealer').onclick=()=>document.getElementById('nxDealerForm').style.display='none';document.getElementById('nxSaveDealer').onclick=()=>{const company=document.getElementById('nxCompany').value.trim();if(!company){alert('Bitte Firma eingeben.');return}const d={id:uid(),company,contact:document.getElementById('nxContact').value.trim(),email:document.getElementById('nxEmail').value.trim(),margin:25,active:document.getElementById('nxActive').value==='1'};dealers.push(d);save(dealers);currentId=d.id;localStorage.setItem(KEY+'-current',d.id);renderModal();applyMargin()};document.getElementById('nxApplyCurrent').onclick=()=>{applyMargin();modal.remove();alert('Händler „'+(current()?.company||'')+'“ ist jetzt aktiv. Vape-Marge: '+clamp(current()?.margin)+'%.')};renderList()}
function renderList(){const box=document.getElementById('nxDealerList');if(!box)return;box.innerHTML=dealers.map(d=>'<div class="nx-dealer-card '+(d.id===currentId?'active':'')+'"><div class="nx-dealer-row"><div><b>'+esc(d.company)+'</b><div class="nx-dealer-note">'+esc(d.contact||'')+(d.email?' · '+esc(d.email):'')+'</div></div><span class="nx-dealer-badge">'+(d.active?'Aktiv':'Inaktiv')+'</span></div><div class="nx-dealer-margin"><label>Marge: <b id="nxMarginLabel-'+d.id+'">'+clamp(d.margin)+'%</b><input data-margin="'+esc(d.id)+'" type="range" min="15" max="25" step="1" value="'+clamp(d.margin)+'"></label></div><div class="nx-dealer-actions"><button class="primary" data-use="'+esc(d.id)+'">Als aktuellen Händler verwenden</button><button data-toggle="'+esc(d.id)+'">'+(d.active?'Deaktivieren':'Aktivieren')+'</button></div></div>').join('');box.querySelectorAll('[data-margin]').forEach(el=>el.oninput=()=>{const d=dealers.find(x=>x.id===el.dataset.margin);if(!d)return;d.margin=clamp(el.value);save(dealers);const lab=document.getElementById('nxMarginLabel-'+d.id);if(lab)lab.textContent=d.margin+'%';if(d.id===currentId)applyMargin()});box.querySelectorAll('[data-use]').forEach(btn=>btn.onclick=()=>{currentId=btn.dataset.use;localStorage.setItem(KEY+'-current',currentId);applyMargin();renderList()});box.querySelectorAll('[data-toggle]').forEach(btn=>btn.onclick=()=>{const d=dealers.find(x=>x.id===btn.dataset.toggle);if(!d)return;d.active=!d.active;save(dealers);renderList()})}
function addEntryButton(){if(document.getElementById('nxDealerOpen'))return true;const more=document.querySelector('#more .menu-grid');if(!more)return false;const b=document.createElement('button');b.id='nxDealerOpen';b.className='menu-card';b.innerHTML='<span>🏪</span><b>Händlerverwaltung</b><small>VAPE · individuelle Marge 15–25 %</small>';b.onclick=renderModal;more.appendChild(b);return true}
function boot(){addEntryButton();applyMargin();setTimeout(addEntryButton,500);setTimeout(addEntryButton,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.neXaroDealer={version:'1.1.0',getDealers:()=>dealers,current:()=>current(),setCurrent:id=>{if(dealers.some(d=>d.id===id)){currentId=id;localStorage.setItem(KEY+'-current',id);applyMargin();return true}return false},getMargin:id=>clamp((dealers.find(d=>d.id===id)||current()||{}).margin),priceFromEk:(ek,margin)=>{const m=clamp(margin);return Number(ek)>0?Number(ek)/(1-m/100):0}};
})();
/* integration trigger */
